# Generated by Django 4.2.dev20221031113113 on 2022-11-12 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources_website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topologyclass',
            old_name='class_id',
            new_name='id',
        ),
    ]
