# Generated by Django 4.2.dev20221031113113 on 2022-12-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_website', '0002_rename_class_id_topologyclass_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='comment',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rev',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='sku',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='workspace',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
