# Generated by Django 4.2.dev20221031113113 on 2022-12-27 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources_website', '0003_alter_resource_comment_alter_resource_is_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.AlterField(
            model_name='resource',
            name='location',
            field=models.ForeignKey(db_column='location', default='Gdansk', on_delete=django.db.models.deletion.CASCADE, to='resources_website.location'),
        ),
    ]
