# Generated by Django 4.2.dev20221031113113 on 2022-12-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_website', '0004_location_alter_resource_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='last_request',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
