# Generated by Django 4.2.dev20221031113113 on 2022-12-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_website', '0006_resource_time_owned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='time_owned',
            field=models.DurationField(null=True),
        ),
    ]
